# Generated by Django 4.2.4 on 2023-11-14 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('med_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('producer', models.CharField(max_length=1000)),
                ('total_amount', models.FloatField(max_length=100000)),
                ('release_form', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('active_element', models.ManyToManyField(related_name='active_element', to='MainApp.activeingredients')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MainApp.category')),
                ('comment', models.ManyToManyField(related_name='comments', to='MainApp.comments')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=10000)),
                ('email', models.EmailField(max_length=1000)),
                ('date_of_birth', models.DateField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MainApp.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Views',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MainApp.medicines')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MainApp.users')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MainApp.users'),
        ),
    ]
