# Generated by Django 4.2.7 on 2023-12-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='release_form',
            field=models.CharField(max_length=1000),
        ),
    ]
