# Generated by Django 4.2.7 on 2023-12-24 22:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 1, 20, 57, 679635)),
        ),
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('symptoms_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MainApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='ChainQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.CharField(max_length=1000)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.users')),
            ],
        ),
    ]
