# Generated by Django 4.2.7 on 2023-12-28 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_alter_requests_date_symptoms_chainqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 28, 9, 11, 45, 166364)),
        ),
        migrations.AddField(
            model_name='medicines',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 28, 9, 11, 45, 168923)),
        ),
    ]
