export const ADMIN_ROUTE = '/admin'
export const REPORT_ROUTE = '/report'
export const LOGIN_ROUTE = '/login'
export const SEARCH_BAR_ROUTE = '/'
export const REGISTRATION_ROUTE = '/registration'
export const SYMPTOM_SEARCH_ROUTE = '/search-by-symptom'
export const ANALOGUE_SEARCH_ROUTE = '/search-by-analogue'
export const NAME_SEARCH_ROUTE = '/search-by-name'
export const PRODUCT_ROUTE = '/product'
export const PERSONAL_ROUTE = '/personal'
export const UPDATE_USER_INFO_ROUTE = '/update-user-info'

